<a href="https://colab.research.google.com/github/amnaayaz896-lang/numpy.tasks/blob/main/python_library_numpy_Amna_Ayaz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class Practice: Student Marks Analyzer

Now we will use different NumPy concepts in one small program.

## Problem

We have marks of different students.

We want to find:

- Average marks
- Highest marks
- Lowest marks
- Passed students
- Failed students
- Total passed students
- Total failed students

In [ ]:
import numpy as np

marks = [30, 40, 80, 70, 10, 20, 60]

average_marks = (np.mean(marks))
print(average_marks)

highest_marks = (np.max(marks))
print(highest_marks)

lowest_marks = (np.min(marks))
print(lowest_marks)

passed_students = marks[marks >= 50]
print(passed_students)

failed_students = marks[marks < 50]
print(failed_students)

44.285714285714285
80
10


TypeError: '>=' not supported between instances of 'list' and 'int'

In [ ]:
import numpy as np

marks = [30, 40, 80, 70, 10, 20, 60]

average_marks = (np.mean(marks))
print(average_marks)

highest_marks = (np.max(marks))
print(highest_marks)

lowest_marks = (np.min(marks))
print(lowest_marks)

pass_students = marks[marks > 50]
print(pass_students)

failed_students = marks[marks < 50]
print(failed_students)

44.285714285714285
80
10


TypeError: '>' not supported between instances of 'list' and 'int'

# Student Practice Tasks

## Task 1

Create this array:

```
10, 20, 30, 40, 50
```

Find:

- Sum
- Average
- Maximum
- Minimum

---

##

## Task 2

Create this array:

```
45, 80, 30, 90, 55, 20
```

Display only the values greater than or equal to `50`.

---

##

## Task 3

Create this array:

```
1, 2, 3, 4, 5, 6
```

Change it into:

```
2 rows
3 columns
```

---

##

## Task 4

Generate `10` random marks between `40` and `100`.

Then find:

- Average
- Highest marks
- Lowest marks

---

##

## Task 5

Create this marks array:

```
35, 67, 89, 45, 90, 22, 70, 58
```
Passing marks are `50`.

Find:

- Passed marks
- Failed marks
- Number of passed students
- Number of failed students

---

#

In [ ]:
import numpy as np

In [ ]:
marks = np.array([10,20,30,40,50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

150
30.0
50
10


In [ ]:
marks = np.array([45,80,30,90,55,20])
print(marks[marks >= 50])


[80 90 55]


In [ ]:
numbers = np.array([1,2,3,4,5,6])
new_numbers = numbers.reshape(2, 3)

print(new_numbers)

[[1 2 3]
 [4 5 6]]


In [ ]:
marks = np.random.randint(40,100,10)
print(marks)

[69 78 84 45 73 72 68 46 43 72]


In [ ]:
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passing_marks = marks[marks >= 50]
failed_marks = marks[marks < 50]
print(passing_marks)
print(failed_marks)
print(len(passing_marks))
print(len(failed_marks))

[67 89 90 70 58]
[35 45 22]
5
3
